---
title: Збереження проекту "Скретч"
hero_image: images / banner.png
description: Збереження проекту "Скретч"
theme: cc-прототип
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "подряпати"
steps:
  - 
    title: Збережіть свій проект
