---
title: Een Scratch-project opslaan
hero_image: images/banner.png
description: Een Scratch-project opslaan
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Sla je project op
