---
title: Чување пројекта Сцратцх
hero_image: имагес / баннер.пнг
description: Чување пројекта Сцратцх
theme: цц-прототип
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "огреботина"
steps:
  - 
    title: Сачувај свој пројекат
