---
title: スクラッチプロジェクトの保存
hero_image: images / banner.png
description: スクラッチプロジェクトの保存
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "スクラッチ"
steps:
  - 
    title: プロジェクトを保存する
