---
title: Lưu dự án Scratch
hero_image: images / banner.png
description: Lưu dự án Scratch
theme: nguyên mẫu cc
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "vết trầy"
steps:
  - 
    title: Lưu dự án của bạn
