---
title: Gem et Scratch-projekt
hero_image: images/banner.png
description: Gem et Scratch-projekt
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Gem dit projekt
