---
title: Gemmer et Scratch-projekt
hero_image: images / banner.png
description: Gemmer et Scratch-projekt
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "kradse"
steps:
  - 
    title: Gem dit projekt
