---
title: Saving a Scratch project
hero_image: images / banner.png
description: Saving a Scratch project
theme: protótipo cc
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "coçar, arranhão"
steps:
  - 
    title: Salve seu projeto
