---
title: Guardar um projeto Scratch
hero_image: images/banner.png
description: Guardar um projeto Scratch
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Guarda o teu projeto
