---
title: Scratch-projektin tallentaminen
hero_image: images/banner.png
description: Scratch-projektin tallentaminen
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Tallenna projektisi
