---
title: Scratch-projektin tallentaminen
hero_image: Kuvien / banner.png
description: Scratch-projektin tallentaminen
theme: CC-prototyyppi
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "naarmu"
steps:
  - 
    title: Tallenna projekti
