---
title: ذخیره کردن یک پروژه‌ی اسکرچ
hero_image: images/banner.png
description: ذخیره کردن یک پروژه‌ی اسکرچ
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: پروژه‌ی خود را ذخیره کنید
