---
title: Guardar un proyecto en Scratch
hero_image: images/banner.png
description: Guardar un proyecto en Scratch
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Guarda tu proyecto
