---
title: Guardar un proyecto Scratch
hero_image: images / banner.png
description: Guardar un proyecto Scratch
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Guarde su proyecto
