---
title: Ein Scratch-Projekt speichern
hero_image: images/banner.png
description: Ein Scratch-Projekt speichern
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Speichere dein Projekt
