---
title: Salvarea unui proiect Scratch
hero_image: images / banner.png
description: Salvarea unui proiect Scratch
theme: cc-prototip
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Salvați proiectul
