---
title: Menyimpan proyek Scratch
hero_image: gambar / banner.png
description: Menyimpan proyek Scratch
theme: cc-prototipe
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Simpan proyek anda
