---
title: Shranjevanje projekta Scratch
hero_image: images / banner.png
description: Shranjevanje projekta Scratch
theme: cc-prototip
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "praska"
steps:
  - 
    title: Shranite svoj projekt
