---
title: A karcolás projekt mentése
hero_image: images / banner.png
description: A karcolás projekt mentése
theme: cc-prototípus
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "karcolás"
steps:
  - 
    title: Mentse el a projektet
