---
title: Scratch projekt mentése
hero_image: images/banner.png
description: Scratch projekt mentése
theme: cc-prototype
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Mentsd el a projektedet
