---
title: Zapisywanie projektu Scratch
hero_image: images / banner.png
description: Zapisywanie projektu Scratch
theme: prototyp cc
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zadraśnięcie"
steps:
  - 
    title: Zapisz swój projekt
