---
title: Uloženie projektu Scratch
hero_image: images / banner.png
description: Uloženie projektu Scratch
theme: cc-prototyp
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "škrabanec"
steps:
  - 
    title: Uložte svoj projekt
