---
title: Menyimpan projek Scratch
hero_image: imej / banner.png
description: Menyimpan projek Scratch
theme: prototaip cc
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "awal"
steps:
  - 
    title: Simpan projek anda
