---
title: Enregistrement d'un projet Scratch
hero_image: images / banner.png
description: Enregistrement d'un projet Scratch
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rayure"
steps:
  - 
    title: Enregistrez votre projet
