---
title: Salvare un progetto di Scratch
hero_image: images/banner.png
description: Salvare un progetto di Scratch
theme: cc-prototype
duration: 1
currciulum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Salva il tuo progetto
