---
title: Bir Scratch projesini kaydetme
hero_image: images / banner.png
description: Bir Scratch projesini kaydetme
theme: cc-prototip
duration: 1
currciulum:
listed: false
ingredient: true
copyedit: true
interests:
technologies: "çizik"
steps:
  - 
    title: Projenizi kaydedin
